import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>How To: Image Filtering</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Oswald&display=swap" rel="stylesheet" />
			</Head>

			<header className={styles.titleContainer}>
				<h1 className={styles.title}>
					HOW IMAGE FILTERING WORKS
				</h1>
				<div className={styles.buttonContainer}>
					<Link href="/beginner/grid_page_beg">
						<div className={styles.button}>
							BEGINNER
						</div>
					</Link>
					<Link href="/">
						<div className={styles.button}>
							INTERMEDIATE
						</div>
					</Link>
					<Link href="/">
						<div className={styles.button}>
							ADVANCED
						</div>
					</Link>
				</div>
			</header>
		</div>
	);
}
