import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>How To: Image Filtering</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.titleContainer}>
                <h1 className={styles.title}>HOW IMAGE FILTERING WORKS</h1>
                <div className={styles.buttonContainer}>
                    <Link href="/beginner/page_1_beg">
                        <div className={styles.button}>BEGINNER</div>
                    </Link>
                    <Link href="/intermediate/page_1_int">
                        <div className={styles.button}>INTERMEDIATE</div>
                    </Link>
                    <Link href="/advanced/page_1_ad">
                        <div className={styles.button}>ADVANCED</div>
                    </Link>
                </div>
            </header>
        </div>
    );
}
